import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ListResourcesRequestSchema,
  ListResourceTemplatesRequestSchema,
  ReadResourceRequestSchema,
  ListPromptsRequestSchema,
  GetPromptRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { MindGraph } from "mindgraph";
import { loadHookEnv, stableAgentId } from "./hook-env.js";
import { handleTool, toolsForProfile } from "./tools.js";
import { getGeneratedTools, handleGeneratedTool } from "./generated-tools.js";
import { checkMcpGovernance } from "./governance.js";
import {
  RESOURCES,
  RESOURCE_TEMPLATES,
  readGovernedResource,
} from "./resources.js";
import path from "node:path";
import {
  refreshHookRunner,
  refreshOwnedClaudeHooks,
  versionSkewNote,
} from "./hook-installer.js";

declare const __PACKAGE_VERSION__: string;

// ── Configuration ─────────────────────────────────────────────────────

const API_KEY = process.env.MINDGRAPH_API_KEY;
const BASE_URL =
  process.env.MINDGRAPH_BASE_URL || "https://api.mindgraph.cloud";
// Must resolve to the SAME identity as the hooks (hook-env resolution): the
// hooks claim/heartbeat leases under this id, and every tool call carries it
// as agent_id. Two different defaults meant the model's fenced writes fought
// the hook's lease on the server — an unwinnable 409 ping-pong.
const AGENT_ID =
  process.env.MINDGRAPH_AGENT_ID || loadHookEnv().agentId || stableAgentId();
const ORG_ID = process.env.MINDGRAPH_ORG_ID;
const PROFILE = process.env.MINDGRAPH_PROFILE || "general";
const HARNESS = process.env.MINDGRAPH_HARNESS || "generic";

if (!API_KEY) {
  console.error(
    "Error: MINDGRAPH_API_KEY environment variable is required.\n" +
      "Get your API key at https://mindgraph.cloud/dashboard/keys\n" +
      "Or run: npx mindgraph-mcp init"
  );
  process.exit(1);
}

// ── MindGraph Client ──────────────────────────────────────────────────

const client = new MindGraph({
  baseUrl: BASE_URL,
  apiKey: API_KEY,
  orgId: ORG_ID,
  // Available in the companion mindgraph SDK from the D6 telemetry batch.
  // Cast keeps this repository buildable during the cross-package release
  // window where npm may still resolve the preceding SDK declaration file.
  telemetrySurface: "mcp",
} as ConstructorParameters<typeof MindGraph>[0] & { telemetrySurface: "mcp" });

// ── Server Instructions ───────────────────────────────────────────────

let INSTRUCTIONS = `You have access to a persistent knowledge graph via MindGraph, plus any ontology tools generated by the active schema.

## Default memory workflow: orient → answer → preserve

**Orient only when prior durable state may matter.** Self-contained questions do not require a memory call or a warm-up sequence.

- Resuming work, asking what was in progress, or continuing a task: call \`mindgraph_memory\` once with action \`context\` and mode \`resume\` or \`continuity\`. This uses authoritative, task-first, lease-aware work state.
- Asking about a topic that may depend on prior knowledge: call \`mindgraph_memory\` once with action \`context\`, mode \`topic\`, and 1–3 discriminating keywords.
- Asking about integration capability or automatic behavior: call \`mindgraph_memory\` with action \`status\`.
- Use the comprehensive read tools below only when the high-level result is insufficient or the user asks for a specific graph operation.

**Answer from the bounded result.** Treat superseded, refuted, or out-of-validity items as warnings, not current facts. Retrieval proves only that the server returned context; it does not prove that a host automatically injected or used it.

**Preserve selectively after material durable change.** Use the existing typed write tool for a fact, correction, decision, work-state transition, or reusable lesson. Do not write ephemeral conversation, routine mechanics, unsupported guesses, or information already represented accurately. An explicit no-write is the correct outcome when nothing durable changed.

## Topic retrieval details

Topic context is graph-only by default. Set \`include_chunks: true\` only for source text needed for quotes, citations, or missing detail. Query with a few proper nouns or technical terms rather than a full sentence. If keyword retrieval fails, use \`mindgraph_retrieve\` with \`semantic\` or \`hybrid\`; use \`document_index\` to inspect ingested sources.

## Comprehensive read tools

- Explicit graph inventory or state questions → the matching \`mindgraph_retrieve\` action such as \`document_index\`, \`active_goals\`, or \`open_questions\`
- Advice or recommendations → \`mindgraph_retrieve\` action \`preferences\`, with topic keywords
- Explore around a known node → \`mindgraph_retrieve\` action \`neighborhood\` with start_uid
- Find connections between nodes → \`mindgraph_retrieve\` action \`path\` with start_uid + end_uid

## When to WRITE

Capture knowledge when the user shares something worth remembering:
- People/orgs/places/events → \`mindgraph_capture\` action "entity"
- Quick notes, preferences → \`mindgraph_capture\` action "journal"
- Factual observations → \`mindgraph_capture\` action "observation"
- Claims with evidence → \`mindgraph_reason\` action "claim"
- Questions to track → \`mindgraph_reason\` action "open_question"
- Goals or projects → \`mindgraph_commit\` action "goal"/"project"
- Decisions → \`mindgraph_commit\` action "open_decision"
- Durable engineering work that must survive sessions/harnesses → \`mindgraph_plan\`
- Typed code anchors, attached memory/work, callers/callees, or impact → \`mindgraph_code\`
- Reusable learning from a material attempt → \`mindgraph_capture\` action "lesson"
- Long-form content → \`mindgraph_ingest\`
- Cross-document synthesis over a project corpus → \`mindgraph_synthesize\` (action "signals" for structural signals; action "run" to spawn a synthesis job that writes Article nodes)

## Tool tips

- Use the harness todo list to organize only the current harness's local execution. Use \`mindgraph_plan\` when work is authoritative across sessions/harnesses, needs graph relationships or evidence, or must be visible to other agents. Do not maintain the same item in both.
- If a local harness task remains unfinished and should become authoritative outside that local list, promote it once with a stable idempotency key when the graph-managed composite actions are available; otherwise do not copy it.
- \`capture\`: "entity"/"observation" for facts, "journal" for personal/informal
- \`reason\`: "claim" when evidence exists, "open_question"/"hypothesis" otherwise
- \`retrieve\`: "context" returns graph nodes only by default — set include_chunks=true for source text
- \`retrieve\`: "context" (FTS default) → "semantic" (conceptual fallback) → "hybrid" (both)
- \`retrieve\`: "neighborhood"/"chain"/"path"/"subgraph" for graph exploration
- \`code\`: pass path + symbol + signature when names are overloaded; ambiguity never writes
- Confidence: 0.9+ for facts, 0.5-0.8 for uncertain, <0.5 for speculation
- Don't narrate tool usage — capture naturally as part of conversation`;

if (PROFILE === "coding") {
  INSTRUCTIONS += `

## Coding profile

**Coding recall order:**
- "What was I working on?" / current work state / resuming anything: call \`mindgraph_memory\` action \`context\`, mode \`resume\` FIRST. It delegates to structural \`resume_work\`; never answer work state from keyword search ("recent work" famously retrieves people named Work).
- Knowledge about specific code (a function, file, or route): \`mindgraph_code\` action \`recall\` — anchor-based, not keyword-based.
- Broad knowledge searches: \`mindgraph_retrieve\` as usual, but when searching for work artifacts pass node_types filters (Task, Lesson, RiskAssessment, Claim) to keep personal-graph content out of engineering answers.

- Use mindgraph_sync for explicit, one-way project memory-file imports. It discovers and hashes files, but you deliberately map durable assertions with record; it never writes graph state back to files.
- Capture corrections, decisions with rationale, fixes that survived meaningful failed attempts, durable invariants/preferences, and blockers with evidence.
- If a write returns \`near_duplicate\`, choose \`reuse_uid\` or \`supersedes_uid\`; use \`confirm_new\` only for genuinely distinct facts.
- Do not capture routine mechanics, transient command output, facts cheaply derivable from code, unsupported speculation as high-confidence lessons, or completion without evidence.
- Adapter context is owned by ${HARNESS}; omit invocation_context because hooks replace it.`;
} else {
  INSTRUCTIONS = INSTRUCTIONS.split("\n")
    .filter(
      (line) =>
        !line.includes("mindgraph_code") &&
        !line.includes("`code`") &&
        !line.includes("Typed code anchors"),
    )
    .join("\n");
}

// Self-heal the pinned hook runner: the registration floats on `npx
// @latest`, so the freshest code in the system is this server — let it
// refresh the runner (and the owned hook entries' timeout budgets) instead
// of asking every machine to re-run install-hooks after each release. The
// bundled cli.js ships as a sibling of this file; in dev/test there is no
// sibling bundle and the refresh is a no-op.
const RUNNER_REFRESH = (() => {
  try {
    return refreshHookRunner(__PACKAGE_VERSION__, path.join(__dirname, "cli.js"));
  } catch {
    return undefined;
  }
})();
if (RUNNER_REFRESH?.refreshed) {
  const refreshedSettings = (() => {
    try {
      return refreshOwnedClaudeHooks();
    } catch {
      return [] as string[];
    }
  })();
  console.error(
    `[mindgraph-mcp] refreshed pinned hook runner ` +
      `${RUNNER_REFRESH.runnerVersion ? `v${RUNNER_REFRESH.runnerVersion}` : "(pre-sidecar)"}` +
      ` → v${__PACKAGE_VERSION__}` +
      (refreshedSettings.length > 0
        ? `; refreshed owned hook entries in ${refreshedSettings.join(", ")}`
        : ""),
  );
}

// Hook/server version skew: after a successful refresh the sidecar matches
// and this stays silent; it fires only when the self-heal was opted out,
// guarded (downgrade), or failed — a 0.14-era runner silently served
// 0.17-era sessions for two weeks before these checks existed.
const HOOK_SKEW_NOTE = (() => {
  try {
    return versionSkewNote(__PACKAGE_VERSION__);
  } catch {
    return undefined;
  }
})();
if (HOOK_SKEW_NOTE) {
  INSTRUCTIONS += `\n\n${HOOK_SKEW_NOTE}`;
  console.error(`[mindgraph-mcp] ${HOOK_SKEW_NOTE}`);
}

// ── MCP Server ────────────────────────────────────────────────────────

const server = new Server(
  {
    name: "mindgraph",
    version: __PACKAGE_VERSION__,
  },
  {
    capabilities: {
      tools: {},
      resources: {},
      prompts: {},
    },
    instructions: INSTRUCTIONS,
  }
);

// ── Tool Handlers ─────────────────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => {
  // Static tools + per-object-type read tools generated from the active
  // ontology (never throws — empty set if the manifest endpoint is absent).
  const generated = await getGeneratedTools(client);
  return { tools: [...toolsForProfile(PROFILE), ...generated.tools] };
});

const GOVERNANCE_CONFIG = {
  baseUrl: BASE_URL,
  apiKey: API_KEY,
  orgId: ORG_ID,
  agentId: AGENT_ID,
  get disabled() {
    return process.env.MINDGRAPH_GOVERNANCE === "off";
  },
};

const MEMORY_RUNTIME_CONFIG = {
  serverVersion: __PACKAGE_VERSION__,
  baseUrl: BASE_URL,
  profile: PROFILE,
  harness: HARNESS,
  orgId: ORG_ID,
  agentId: AGENT_ID,
};

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  const rawArgs = { ...((args as Record<string, unknown>) || {}) };
  // Inject default agent_id if not provided. Static tools declare agent_id;
  // generated ontology tools do not, and their schemas reject it — so the
  // injected copy is kept separate from the args they receive.
  const toolArgs = { ...rawArgs };
  if (!toolArgs.agent_id) {
    toolArgs.agent_id = AGENT_ID;
  }

  const governance = await checkMcpGovernance(name, toolArgs, GOVERNANCE_CONFIG);
  if (!governance.allowed) {
    return {
      content: [{ type: "text", text: JSON.stringify({ error: governance.message, ...governance }) }],
      isError: true,
    };
  }

  // Route schema-qualified generated ontology tools, including relation-role
  // reads and the structured composite.
  const generated = await getGeneratedTools(client);
  const desc = generated.byName.get(name);
  if (desc) {
    return handleGeneratedTool(client, desc, rawArgs);
  }

  return handleTool(client, name, toolArgs, MEMORY_RUNTIME_CONFIG);
});

// ── Prompts ───────────────────────────────────────────────────────────

const PROMPTS = [
  {
    name: "graph-summary",
    description:
      "Get a comprehensive summary of what's in your knowledge graph — entities, claims, goals, and open questions.",
    arguments: [],
  },
  {
    name: "active-goals",
    description:
      "Review your active goals, projects, and milestones with their current status.",
    arguments: [],
  },
  {
    name: "open-questions",
    description:
      "List all open questions and hypotheses that need investigation.",
    arguments: [],
  },
  {
    name: "review-contradictions",
    description:
      "Find and analyze contradictions in your knowledge graph — claims that conflict with each other.",
    arguments: [],
  },
  {
    name: "knowledge-about",
    description:
      "Retrieve everything the knowledge graph knows about a specific topic.",
    arguments: [
      {
        name: "topic",
        description: "The topic to search for",
        required: true,
      },
    ],
  },
  {
    name: "daily-briefing",
    description:
      "Get a daily briefing: active goals, recent knowledge, open questions, and pending decisions.",
    arguments: [],
  },
  {
    name: "capture-conversation",
    description:
      "Analyze the current conversation and capture all important entities, claims, decisions, and action items into the knowledge graph.",
    arguments: [
      {
        name: "conversation",
        description: "The conversation text to analyze and capture",
        required: true,
      },
    ],
  },
];

server.setRequestHandler(ListPromptsRequestSchema, async () => {
  return { prompts: PROMPTS };
});

server.setRequestHandler(GetPromptRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  switch (name) {
    case "graph-summary":
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: "Give me a comprehensive summary of my knowledge graph. Start by checking the graph stats, then retrieve my active goals, open questions, and any recent knowledge. Organize the summary by cognitive layer (Reality, Epistemic, Intent, Action, Memory).",
            },
          },
        ],
      };

    case "active-goals":
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: "Review all my active goals, projects, and milestones. For each one, show its status, any linked decisions or tasks, and suggest next steps. Group them by project if applicable.",
            },
          },
        ],
      };

    case "open-questions":
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: "List all my open questions and hypotheses. For each one, check if there's any related evidence or claims in the graph that might help answer them. Prioritize by salience and suggest which ones I should investigate first.",
            },
          },
        ],
      };

    case "review-contradictions":
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: "Search my knowledge graph for contradictions — claims that conflict with each other, or evidence that undermines existing beliefs. Also look for weak claims (low confidence) that might need more evidence. For each contradiction found, explain the conflict and suggest how to resolve it.",
            },
          },
        ],
      };

    case "knowledge-about": {
      const topic = args?.topic || "general";
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: `Search my knowledge graph for everything related to "${topic}". Use context retrieval with short BM25 keyword queries (1–3 discriminating terms extracted from the topic, not full sentences). Try multiple keyword variations and synonyms to ensure broad coverage. Present a structured overview of what I know about this topic, highlighting any gaps or open questions.`,
            },
          },
        ],
      };
    }

    case "daily-briefing":
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: "Give me a daily briefing. Check:\n1. Active goals and their progress\n2. Open decisions that need resolution\n3. Recent knowledge added in the last few days\n4. Open questions worth investigating\n5. Any pending approvals\n6. Weak claims that need more evidence\n\nKeep it concise and actionable — highlight what needs my attention today.",
            },
          },
        ],
      };

    case "capture-conversation": {
      const conversation = args?.conversation || "";
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: `Analyze the following conversation and capture all important information into my knowledge graph. Extract:\n- Named entities (people, organizations, places, events) → mindgraph_capture action "entity"\n- Factual claims and observations → mindgraph_capture action "observation" or mindgraph_reason action "claim"\n- Decisions made or pending → mindgraph_commit action "open_decision"\n- Goals or commitments mentioned → mindgraph_commit action "goal"/"project"\n- Open questions raised → mindgraph_reason action "open_question"\n- Any hypotheses or theories discussed → mindgraph_reason action "hypothesis"/"theory"\n\nConversation:\n${conversation}`,
            },
          },
        ],
      };
    }

    default:
      throw new Error(`Unknown prompt: ${name}`);
  }
});

// ── Static Resources ──────────────────────────────────────────────────

server.setRequestHandler(ListResourcesRequestSchema, async () => {
  return { resources: RESOURCES };
});

// ── Resource Templates ────────────────────────────────────────────────

server.setRequestHandler(ListResourceTemplatesRequestSchema, async () => {
  return { resourceTemplates: RESOURCE_TEMPLATES };
});

// ── Resource Reader (static + dynamic) ────────────────────────────────

server.setRequestHandler(ReadResourceRequestSchema, async (request) => {
  return readGovernedResource(
    client,
    request.params.uri,
    GOVERNANCE_CONFIG,
    MEMORY_RUNTIME_CONFIG,
  );
});

// ── Start ─────────────────────────────────────────────────────────────

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(
    `MindGraph MCP server v${__PACKAGE_VERSION__} running on stdio (${BASE_URL})`
  );
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
